In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

pd.options.display.float_format = '{:.2f}'.format

In [3]:
df_balance_resume_tri = pd.read_csv(r"C:\Users\usuario\Desktop\Programacao\financeml\src\data\dados_tratados\df_balancedata_tri_final.csv")

In [4]:
pd.DataFrame(df_balance_resume_tri)

,Unnamed: 0,CNPJ,Ticker,DENOM_CIA,CD_CVM,DT_FIM_EXERC,1 - Ativo Total,1.01 - Ativo Circulante,2.01 - Passivo Circulante,2.02 - Passivo Não Circulante,Patrimonio_Liquido_Unificado
0,0,191,BBAS3,BCO BRASIL S.A.,1023,2014-03-31,1294187527.00,753744537.00,839101217.00,NaN,71464555.00
1,1,191,BBAS3,BCO BRASIL S.A.,1023,2014-06-30,1344627835.00,739026339.00,886841959.00,NaN,69442420.00
2,2,191,BBAS3,BCO BRASIL S.A.,1023,2014-09-30,1369739682.00,770692909.00,907583262.00,NaN,78845901.00
3,3,191,BBAS3,BCO BRASIL S.A.,1023,2015-03-31,1465549447.00,730302299.00,979510346.00,NaN,72600519.00
4,4,191,BBAS3,BCO BRASIL S.A.,1023,2015-06-30,1460958067.00,726631228.00,959522792.00,NaN,71944144.00
...,...,...,...,...,...,...,...,...,...,...,...
14726,14726,97837181000147,DXCO3,DURATEX S.A.,21091,2015-06-30,7785597.00,2245845.00,996547.00,2178711.00,4610339.00
14727,14727,97837181000147,DXCO3,DURATEX S.A.,21091,2015-09-30,8184089.00,2417760.00,933529.00,2577259.00,4673301.00
14728,14728,97837181000147,DXCO3,DURATEX S.A.,21091,2016-03-31,7726074.00,2060509.00,1064287.00,2184844.00,4476943.00
14729,14729,97837181000147,DXCO3,DURATEX S.A.,21091,2016-06-30,7675312.00,2207580.00,1083777.00,2052541.00,4538994.00
14730,14730,97837181000147,DXCO3,DURATEX S.A.,21091,2016-09-30,7590040.00,2069928.00,860269.00,2160277.00,4569494.00

In [5]:
df_balance_resume_tri.columns

Index(['Unnamed: 0', 'CNPJ', 'Ticker', 'DENOM_CIA', 'CD_CVM', 'DT_FIM_EXERC',
       '1 - Ativo Total', '1.01 - Ativo Circulante',
       '2.01 - Passivo Circulante', '2.02 - Passivo Não Circulante',
       'Patrimonio_Liquido_Unificado'],
      dtype='object')

In [6]:
df_balance_resume_tri

,Unnamed: 0,CNPJ,Ticker,DENOM_CIA,CD_CVM,DT_FIM_EXERC,1 - Ativo Total,1.01 - Ativo Circulante,2.01 - Passivo Circulante,2.02 - Passivo Não Circulante,Patrimonio_Liquido_Unificado
0,0,191,BBAS3,BCO BRASIL S.A.,1023,2014-03-31,1294187527.00,753744537.00,839101217.00,NaN,71464555.00
1,1,191,BBAS3,BCO BRASIL S.A.,1023,2014-06-30,1344627835.00,739026339.00,886841959.00,NaN,69442420.00
2,2,191,BBAS3,BCO BRASIL S.A.,1023,2014-09-30,1369739682.00,770692909.00,907583262.00,NaN,78845901.00
3,3,191,BBAS3,BCO BRASIL S.A.,1023,2015-03-31,1465549447.00,730302299.00,979510346.00,NaN,72600519.00
4,4,191,BBAS3,BCO BRASIL S.A.,1023,2015-06-30,1460958067.00,726631228.00,959522792.00,NaN,71944144.00
...,...,...,...,...,...,...,...,...,...,...,...
14726,14726,97837181000147,DXCO3,DURATEX S.A.,21091,2015-06-30,7785597.00,2245845.00,996547.00,2178711.00,4610339.00
14727,14727,97837181000147,DXCO3,DURATEX S.A.,21091,2015-09-30,8184089.00,2417760.00,933529.00,2577259.00,4673301.00
14728,14728,97837181000147,DXCO3,DURATEX S.A.,21091,2016-03-31,7726074.00,2060509.00,1064287.00,2184844.00,4476943.00
14729,14729,97837181000147,DXCO3,DURATEX S.A.,21091,2016-06-30,7675312.00,2207580.00,1083777.00,2052541.00,4538994.00
14730,14730,97837181000147,DXCO3,DURATEX S.A.,21091,2016-09-30,7590040.00,2069928.00,860269.00,2160277.00,4569494.00

In [7]:
df_dre = pd.read_csv(r"C:\Users\usuario\Desktop\Programacao\financeml\src\data\dados_tratados\dre_tri_res.csv")
pd.DataFrame(df_dre)

,Unnamed: 0,CNPJ,Ticker,DENOM_CIA,CD_CVM,DT_FIM_EXERC,Lucro/Prejuízo Consolidado
0,0,191,BBAS3,BCO BRASIL S.A.,1023,2014-03-31,2774858.00
1,1,191,BBAS3,BCO BRASIL S.A.,1023,2014-06-30,4177761.00
2,2,191,BBAS3,BCO BRASIL S.A.,1023,2014-09-30,5525412.00
3,3,191,BBAS3,BCO BRASIL S.A.,1023,2015-03-31,5675916.00
4,4,191,BBAS3,BCO BRASIL S.A.,1023,2015-06-30,5768503.00
...,...,...,...,...,...,...,...
14484,14484,97837181000147,DXCO3,DURATEX S.A.,21091,2015-06-30,70214.50
14485,14485,97837181000147,DXCO3,DURATEX S.A.,21091,2015-09-30,79926.50
14486,14486,97837181000147,DXCO3,DURATEX S.A.,21091,2016-03-31,-31122.00
14487,14487,97837181000147,DXCO3,DURATEX S.A.,21091,2016-06-30,-15678.00
14488,14488,97837181000147,DXCO3,DURATEX S.A.,21091,2016-09-30,14123.50

In [8]:
# Realizar a união das duas tabelas com base em 'CNPJ_CIA' e 'DT_FIM_EXERC'
df_merged = pd.merge(df_dre, df_balance_resume_tri, on=['CNPJ', 'DT_FIM_EXERC'], how='inner')

# Remover as colunas 'Unnamed' geradas pelo índice e colunas duplicadas
df_merged = df_merged.drop(columns=['Unnamed: 0_x', 'Unnamed: 0_y', 'DENOM_CIA_y', 'CD_CVM_y'])

# Renomear as colunas que permaneceram com sufixo para seus nomes originais
df_cleaned = df_merged.rename(columns={
    'DENOM_CIA_x': 'DENOM_CIA',
    'CD_CVM_x': 'CD_CVM'
})

df_cleaned

,CNPJ,Ticker_x,DENOM_CIA,CD_CVM,DT_FIM_EXERC,Lucro/Prejuízo Consolidado,Ticker_y,1 - Ativo Total,1.01 - Ativo Circulante,2.01 - Passivo Circulante,2.02 - Passivo Não Circulante,Patrimonio_Liquido_Unificado
0,191,BBAS3,BCO BRASIL S.A.,1023,2014-03-31,2774858.00,BBAS3,1294187527.00,753744537.00,839101217.00,NaN,71464555.00
1,191,BBAS3,BCO BRASIL S.A.,1023,2014-06-30,4177761.00,BBAS3,1344627835.00,739026339.00,886841959.00,NaN,69442420.00
2,191,BBAS3,BCO BRASIL S.A.,1023,2014-09-30,5525412.00,BBAS3,1369739682.00,770692909.00,907583262.00,NaN,78845901.00
3,191,BBAS3,BCO BRASIL S.A.,1023,2015-03-31,5675916.00,BBAS3,1465549447.00,730302299.00,979510346.00,NaN,72600519.00
4,191,BBAS3,BCO BRASIL S.A.,1023,2015-06-30,5768503.00,BBAS3,1460958067.00,726631228.00,959522792.00,NaN,71944144.00
...,...,...,...,...,...,...,...,...,...,...,...,...
26704,97837181000147,DXCO3,DURATEX S.A.,21091,2015-06-30,70214.50,DXCO3,7785597.00,2245845.00,996547.00,2178711.00,4610339.00
26705,97837181000147,DXCO3,DURATEX S.A.,21091,2015-09-30,79926.50,DXCO3,8184089.00,2417760.00,933529.00,2577259.00,4673301.00
26706,97837181000147,DXCO3,DURATEX S.A.,21091,2016-03-31,-31122.00,DXCO3,7726074.00,2060509.00,1064287.00,2184844.00,4476943.00
26707,97837181000147,DXCO3,DURATEX S.A.,21091,2016-06-30,-15678.00,DXCO3,7675312.00,2207580.00,1083777.00,2052541.00,4538994.00
26708,97837181000147,DXCO3,DURATEX S.A.,21091,2016-09-30,14123.50,DXCO3,7590040.00,2069928.00,860269.00,2160277.00,4569494.00

In [9]:
# Calculando os indicadores fundamentais

# ROE (Return on Equity)
df_cleaned['ROE (%)'] = (df_cleaned['Lucro/Prejuízo Consolidado'] / df_cleaned['Patrimonio_Liquido_Unificado']) * 100

# ROA (Return on Assets)
df_cleaned['ROA (%)'] = (df_cleaned['Lucro/Prejuízo Consolidado'] / df_cleaned['1 - Ativo Total']) * 100

# Liquidez Corrente
df_cleaned['Liquidez Corrente'] = df_cleaned['1.01 - Ativo Circulante'] / df_cleaned['2.01 - Passivo Circulante']

# Grau de Endividamento
# Como não temos 'Passivo Total', somamos o 'Passivo Circulante' e 'Passivo Não Circulante'
df_cleaned['Passivo Total'] = df_cleaned['2.01 - Passivo Circulante'].fillna(0) + df_cleaned['2.02 - Passivo Não Circulante'].fillna(0)
df_cleaned['Endividamento'] = df_cleaned['Passivo Total'] / df_cleaned['Patrimonio_Liquido_Unificado']

# Cobertura de Passivos (Ativo Circulante / Passivo Total)
df_cleaned['Cobertura de Passivos'] = df_cleaned['1.01 - Ativo Circulante'] / df_cleaned['Passivo Total']

# Taxa de Retorno do Capital (ROC) = (Lucro Líquido / (Ativo Total - Passivo Total)) * 100
df_cleaned['ROC (%)'] = (df_cleaned['Lucro/Prejuízo Consolidado'] / 
                         (df_cleaned['1 - Ativo Total'] - df_cleaned['Passivo Total'])) * 100

# Exibir as primeiras linhas da tabela consolidada
df_cleaned

,CNPJ,Ticker_x,DENOM_CIA,CD_CVM,DT_FIM_EXERC,Lucro/Prejuízo Consolidado,Ticker_y,1 - Ativo Total,1.01 - Ativo Circulante,2.01 - Passivo Circulante,2.02 - Passivo Não Circulante,Patrimonio_Liquido_Unificado,ROE (%),ROA (%),Liquidez Corrente,Passivo Total,Endividamento,Cobertura de Passivos,ROC (%)
0,191,BBAS3,BCO BRASIL S.A.,1023,2014-03-31,2774858.00,BBAS3,1294187527.00,753744537.00,839101217.00,NaN,71464555.00,3.88,0.21,0.90,839101217.00,11.74,0.90,0.61
1,191,BBAS3,BCO BRASIL S.A.,1023,2014-06-30,4177761.00,BBAS3,1344627835.00,739026339.00,886841959.00,NaN,69442420.00,6.02,0.31,0.83,886841959.00,12.77,0.83,0.91
2,191,BBAS3,BCO BRASIL S.A.,1023,2014-09-30,5525412.00,BBAS3,1369739682.00,770692909.00,907583262.00,NaN,78845901.00,7.01,0.40,0.85,907583262.00,11.51,0.85,1.20
3,191,BBAS3,BCO BRASIL S.A.,1023,2015-03-31,5675916.00,BBAS3,1465549447.00,730302299.00,979510346.00,NaN,72600519.00,7.82,0.39,0.75,979510346.00,13.49,0.75,1.17
4,191,BBAS3,BCO BRASIL S.A.,1023,2015-06-30,5768503.00,BBAS3,1460958067.00,726631228.00,959522792.00,NaN,71944144.00,8.02,0.39,0.76,959522792.00,13.34,0.76,1.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26704,97837181000147,DXCO3,DURATEX S.A.,21091,2015-06-30,70214.50,DXCO3,7785597.00,2245845.00,996547.00,2178711.00,4610339.00,1.52,0.90,2.25,3175258.00,0.69,0.71,1.52
26705,97837181000147,DXCO3,DURATEX S.A.,21091,2015-09-30,79926.50,DXCO3,8184089.00,2417760.00,933529.00,2577259.00,4673301.00,1.71,0.98,2.59,3510788.00,0.75,0.69,1.71
26706,97837181000147,DXCO3,DURATEX S.A.,21091,2016-03-31,-31122.00,DXCO3,7726074.00,2060509.00,1064287.00,2184844.00,4476943.00,-0.70,-0.40,1.94,3249131.00,0.73,0.63,-0.70
26707,97837181000147,DXCO3,DURATEX S.A.,21091,2016-06-30,-15678.00,DXCO3,7675312.00,2207580.00,1083777.00,2052541.00,4538994.00,-0.35,-0.20,2.04,3136318.00,0.69,0.70,-0.35
26708,97837181000147,DXCO3,DURATEX S.A.,21091,2016-09-30,14123.50,DXCO3,7590040.00,2069928.00,860269.00,2160277.00,4569494.00,0.31,0.19,2.41,3020546.00,0.66,0.69,0.31

In [10]:
df_balance_dre_ind = df_cleaned

In [11]:
df_balance_dre_ind.to_csv(r"C:\Users\usuario\Desktop\Programacao\financeml\src\data\dados_tratados\df_balance_dre_ind.csv")

In [12]:
# Salvando no pasta Dados com Métricas

df_balance_dre_ind.to_csv(r'C:\Users\usuario\Desktop\Programacao\financeml\src\data\dados_com_metricas\df_balance_dre_metricas.csv')

In [13]:
cotacao_hist = pd.read_csv(r"C:\Users\usuario\Desktop\Programacao\financeml\src\data\dados_tratados\preco_acoes_final3_cnpj.csv")

In [14]:
cotacao_hist

,data_pregao,CNPJ,cod_negociacao,noma_empresa,preco_ultimo_negocio
0,2016-10-28,42771949000135.00,AALR3,ALLIAR,19.20
1,2016-10-31,42771949000135.00,AALR3,ALLIAR,18.06
2,2016-11-01,42771949000135.00,AALR3,ALLIAR,17.90
3,2016-11-03,42771949000135.00,AALR3,ALLIAR,17.99
4,2016-11-04,42771949000135.00,AALR3,ALLIAR,17.75
...,...,...,...,...,...
599879,2024-05-22,13574594000196.00,ZAMP3,ZAMP S.A.,3.17
599880,2024-05-23,13574594000196.00,ZAMP3,ZAMP S.A.,3.07
599881,2024-05-24,13574594000196.00,ZAMP3,ZAMP S.A.,2.99
599882,2024-05-27,13574594000196.00,ZAMP3,ZAMP S.A.,2.99
599883,2024-05-28,13574594000196.00,ZAMP3,ZAMP S.A.,3.02

In [15]:

# Convert date columns to datetime
df_balance_dre_ind['DT_FIM_EXERC'] = pd.to_datetime(df_balance_dre_ind['DT_FIM_EXERC'])
cotacao_hist['data_pregao'] = pd.to_datetime(cotacao_hist['data_pregao'])

# Function to find the nearest available date
def encontrar_data_proxima(data, datas_disponiveis):
    datas_diferenca = datas_disponiveis - data
    datas_diferenca_pos = datas_diferenca[datas_diferenca >= pd.Timedelta(0)]
    if not datas_diferenca_pos.empty:
        return datas_disponiveis[datas_diferenca_pos.idxmin()]
    return datas_disponiveis[datas_diferenca.abs().idxmin()]

# Transform the unique date series into a list for efficient comparison
datas_unicas = pd.Series(cotacao_hist['data_pregao'].unique())

# Apply the function to find the nearest available date for each record
df_balance_dre_ind['data_pregao'] = df_balance_dre_ind['DT_FIM_EXERC'].apply(lambda x: encontrar_data_proxima(x, datas_unicas))

# Merge the two datasets
df_merged = pd.merge(
    df_balance_dre_ind, 
    cotacao_hist[['CNPJ', 'cod_negociacao', 'data_pregao', 'preco_ultimo_negocio']],
    left_on=['CNPJ', 'data_pregao'], 
    right_on=['CNPJ', 'data_pregao'], 
    how='left'
)

# Sort by CNPJ and DT_FIM_EXERC to prepare for percentage change calculation
df_merged_sorted = df_merged.sort_values(by=['CNPJ', 'DT_FIM_EXERC'])

# Calculate the percentage change in stock prices for each company
df_merged_sorted['variacao_percentual'] = df_merged_sorted.groupby('CNPJ')['preco_ultimo_negocio'].pct_change() * 100

# Remove rows where percentage variation is NaN (resulting from pct_change)
df_merged_sorted.dropna(subset=['variacao_percentual'], inplace=True)

# Optional: Display or save the final dataframe
df_merged_sorted

C:\Users\usuario\AppData\Local\Temp\ipykernel_2100\1134414059.py:32: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  df_merged_sorted['variacao_percentual'] = df_merged_sorted.groupby('CNPJ')['preco_ultimo_negocio'].pct_change() * 100

,CNPJ,Ticker_x,DENOM_CIA,CD_CVM,DT_FIM_EXERC,Lucro/Prejuízo Consolidado,Ticker_y,1 - Ativo Total,1.01 - Ativo Circulante,2.01 - Passivo Circulante,...,ROA (%),Liquidez Corrente,Passivo Total,Endividamento,Cobertura de Passivos,ROC (%),data_pregao,cod_negociacao,preco_ultimo_negocio,variacao_percentual
1,191,BBAS3,BCO BRASIL S.A.,1023,2014-06-30,4177761.00,BBAS3,1344627835.00,739026339.00,886841959.00,...,0.31,0.83,886841959.00,12.77,0.83,0.91,2014-06-30,BBAS3,24.85,8.99
2,191,BBAS3,BCO BRASIL S.A.,1023,2014-09-30,5525412.00,BBAS3,1369739682.00,770692909.00,907583262.00,...,0.40,0.85,907583262.00,11.51,0.85,1.20,2014-09-30,BBAS3,25.30,1.81
3,191,BBAS3,BCO BRASIL S.A.,1023,2015-03-31,5675916.00,BBAS3,1465549447.00,730302299.00,979510346.00,...,0.39,0.75,979510346.00,13.49,0.75,1.17,2015-03-31,BBAS3,22.91,-9.45
4,191,BBAS3,BCO BRASIL S.A.,1023,2015-06-30,5768503.00,BBAS3,1460958067.00,726631228.00,959522792.00,...,0.39,0.76,959522792.00,13.34,0.76,1.15,2015-06-30,BBAS3,24.28,5.98
5,191,BBAS3,BCO BRASIL S.A.,1023,2015-09-30,7317984.50,BBAS3,1510509513.00,737496810.00,954118423.00,...,0.48,0.77,954118423.00,13.18,0.77,1.32,2015-09-30,BBAS3,15.20,-37.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26695,97837181000147,DXCO3,DEXCO S.A.,21091,2022-06-30,280896.00,DXCO3,12423248.00,3834789.00,2564153.00,...,2.26,1.50,6682461.00,1.16,0.57,4.89,2022-06-30,DXCO3,9.87,-32.77
26696,97837181000147,DXCO3,DEXCO S.A.,21091,2022-09-30,350412.50,DXCO3,12479962.00,3778897.00,2461858.00,...,2.81,1.53,6573156.00,1.11,0.57,5.93,2022-09-30,DXCO3,9.35,-5.27
26697,97837181000147,DXCO3,DEXCO S.A.,21091,2023-03-31,147654.00,DXCO3,13239857.00,3312493.00,2372419.00,...,1.12,1.40,7301358.00,1.23,0.45,2.49,2023-03-31,DXCO3,5.88,-37.11
26698,97837181000147,DXCO3,DEXCO S.A.,21091,2023-06-30,231485.00,DXCO3,13638828.00,3202568.00,2789614.00,...,1.70,1.15,7606135.00,1.26,0.42,3.84,2023-06-30,DXCO3,8.35,42.01
26699,97837181000147,DXCO3,DEXCO S.A.,21091,2023-09-30,450032.00,DXCO3,14051331.00,2950952.00,2774281.00,...,3.20,1.06,7639757.00,1.19,0.39,7.02,2023-10-02,DXCO3,7.45,-10.78

In [16]:
df_merged_sorted.to_csv(r"C:\Users\usuario\Desktop\Programacao\financeml\src\data\dados_tratados\df_metrics_cot_bldre.csv")